fix: add team_reviewers to requestReviewers
electron/trop pull request #276
Opened 2024-04-05 23:52 UTC by alicelovescake

This PR:
- [x] Adds `DEFAULT_BACKPORT_REVIEW_TEAM` to missing team_reviewers param in octokit:[ See API doc](https://octokit.github.io/rest.js/v20#pulls-request-reviewers)
- [x] Should fix bug on why releases team is being tagged for automatic or manual backports

2024-04-06 00:03 UTC, alicelovescake commented on src/utils.ts
> +    teamReviewers.push(DEFAULT_BACKPORT_REVIEW_TEAM);
Yes!

2024-04-06 00:19 UTC, dsanders11 requested changes
Doing some search on GitHub to confirm, I think this does need to ensure that only the team slug, (e.g. `wg-releases`, not `electron/wg-releases`) gets used. Examples I found:

* https://github.com/ampproject/cdn-configuration/blob/5f529809a21a875a9a474202b08f06136d481c6a/scripts/promote-job.ts#L165
* https://github.com/leftxs/cloudflare-docs/blob/10574f1ba0192c6f3ba849682a8c5152063ffefb/.github/actions/assign-pr/index.ts#L115-L116

It would be nice to handle both cases since then we don't have to bug anyone about changing it if the current format is the prefixed version.

2024-04-06 00:48 UTC, alicelovescake commented
> Doing some search on GitHub to confirm, I think this does need to ensure that only the team slug, (e.g. `wg-releases`, not `electron/wg-releases`) gets used. Examples I found:
> 
> * https://github.com/ampproject/cdn-configuration/blob/5f529809a21a875a9a474202b08f06136d481c6a/scripts/promote-job.ts#L165
> * https://github.com/leftxs/cloudflare-docs/blob/10574f1ba0192c6f3ba849682a8c5152063ffefb/.github/actions/assign-pr/index.ts#L115-L116
> 
> It would be nice to handle both cases since then we don't have to bug anyone about changing it if the current format is the prefixed version.

Nice call! New changes should handle both the case that we have electron/wg-releases or if in the future we change it to just wg-releases. 
`    const slug = DEFAULT_BACKPORT_REVIEW_TEAM.split('/')[1];
    teamReviewers.push(slug ? slug : DEFAULT_BACKPORT_REVIEW_TEAM);`

2024-04-07 22:30 UTC, dsanders11 commented on src/utils.ts
> +    teamReviewers.push(slug ? slug : DEFAULT_BACKPORT_REVIEW_TEAM);
```suggestion
    const slug = DEFAULT_BACKPORT_REVIEW_TEAM.split('/')[1] || DEFAULT_BACKPORT_REVIEW_TEAM;
    teamReviewers.push(slug);
```

Suggestion for readability. Functionally equivalent, but I think it's more readable than a ternary in this case.

2024-04-07 22:34 UTC, alicelovescake commented on src/utils.ts
> +    teamReviewers.push(slug ? slug : DEFAULT_BACKPORT_REVIEW_TEAM);
Agreed! Change made

2024-04-07 22:43 UTC, dsanders11 approved these changes

2024-04-08 14:18 UTC, codebytere approved these changes

2024-04-08 16:24 UTC, merged