refactor: add try catch to reviewer
electron/trop pull request #279
Opened 2024-04-09 22:19 UTC by alicelovescake

This PR: 

- [x] Adds a try catch block so we can log the error and not stop the process if requestReviewer fails

2024-04-09 22:35 UTC, dsanders11 requested changes

2024-04-09 22:35 UTC, dsanders11 commented on src/utils.ts
> +      );
```suggestion
      log(
        'tagBackportReviewers',
        LogLevel.ERROR,
        `Failed to request reviewers for PR #${targetPrNumber}`,
        error,
      );
```

There's a dedicated log util which is used elsewhere in this file, so let's stay consistent and use it here as well.

2024-04-10 01:45 UTC, dsanders11 requested changes
I think the changes to tests should mostly be backed out and put in a new `spec/utils.spec.ts` which tests `tagBackportReviewers` directly. The changes to `spec/operations.spec.ts` get too into the implementation details of `tagBackportReviewers`, it was better when it was checking just if `tagBackportReviewers` was called, and we can put testing of error handling inside `tagBackportReviewers` in the `spec/utils.spec.ts` file.

2024-04-10 02:40 UTC, alicelovescake commented
> I think the changes to tests should mostly be backed out and put in a new `spec/utils.spec.ts` which tests `tagBackportReviewers` directly. The changes to `spec/operations.spec.ts` get too into the implementation details of `tagBackportReviewers`, it was better when it was checking just if `tagBackportReviewers` was called, and we can put testing of error handling inside `tagBackportReviewers` in the `spec/utils.spec.ts` file.

Ah yes, agreed that for the updateManualBackport function, it was testing the implementation details of tagBackportReviewers more. Made a new test file with similar changes + a test checking that users is added to reviewers correctly

2024-04-10 17:34 UTC, dsanders11 approved these changes
Thanks @alicelovescake!

2024-04-10 18:15 UTC, merged