refactor: improve branch support logic
electron/trop pull request #301
Opened 2024-08-19 08:17 UTC by codebytere

Secondary to https://github.com/electron/trop/pull/300

Cleans up some comment-initiated backport logic

2024-08-19 18:19 UTC, ckerr commented on src/index.ts
> -            if (!branch.trim()) continue;
Agree that the `trim()` call is redundant after `b.trim()`, but do we need to still check whether `branch` is empty? Or add a `.filter()` after `.map()` to remove empty strings?

2024-08-20 19:50 UTC, jkleinsc requested changes
Maybe I am missing something here, but it looks like this change moves the check for branch existence to only fire when NO_EOL_SUPPORT is set?

2024-08-20 19:50 UTC, jkleinsc commented on src/index.ts
> +
Why is this block moved under the section flagged by NO_EOL_SUPPORT?

2024-08-21 08:19 UTC, codebytere commented on src/index.ts
> +
`getSupportedBranches` itself checks branch existence - so in moving it down we save a redundant check in the case the variable is set.

2024-08-21 08:21 UTC, codebytere commented
@jkleinsc 

>  check for branch existence to only fire when NO_EOL_SUPPORT is set?

it moves the conditional down, but not inside the check - if `NO_EOL_SUPPORT` the check still runs.

2024-08-21 19:54 UTC, jkleinsc approved these changes

2024-08-22 13:38 UTC, merged