fix: ensure git found on trop runner
electron/trop pull request #304
Opened 2024-08-23 08:24 UTC by codebytere

Closes https://github.com/electron/trop/issues/303.

2024-08-23 14:58 UTC, ckerr approved these changes

2024-08-23 19:47 UTC, dsanders11 requested changes

2024-08-23 19:47 UTC, dsanders11 commented on app.json
>      }
```suggestion
  "buildpacks": [
    {
      "url": "heroku-community/apt"
    },
    {
      "url": "heroku/nodejs"
    }
```

I'm not sure it would matter in this case, but from the [Heroku docs for multiple buildpacks](https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app):

> The buildpack for the **primary language** of your app should always be the **last** buildpack in the list. This ensures that defaults for that primary language are applied instead of those for another language, and allows Heroku to correctly detect the primary language of your app.

2024-08-26 15:27 UTC, MarshallOfSound commented on src/utils.ts
> +  const gitExists = execSync('which git').toString().trim();
Should we do this on startup instead of during a backport? Then trop won't even start if we don't have git

2024-08-26 16:13 UTC, codebytere commented on src/utils.ts
> +  const gitExists = execSync('which git').toString().trim();
done

2024-08-26 16:24 UTC, MarshallOfSound commented on src/index.ts
> +    execSync('which git').toString().trim();
Double?

2024-08-26 16:24 UTC, MarshallOfSound commented on src/index.ts
> +  const checkGitExists = async () => {
Doesn't have to be async

2024-08-26 16:24 UTC, MarshallOfSound commented on src/utils.ts
> +  const gitExists = execSync('which git').toString().trim();
Can be removed now it's top level

2024-08-26 16:35 UTC, codebytere commented on src/index.ts
> +  const checkGitExists = async () => {
oops leftover from when i used trop to make a comment!

2024-08-27 04:00 UTC, dsanders11 approved these changes

2024-09-04 11:35 UTC, merged