fix: remove needs-manual label from original PR
electron/trop pull request #306
Opened 2024-09-10 08:22 UTC by codebytere

Closes https://github.com/electron/trop/issues/297.

Ensures that when a backport PR is opened manually, and then target labels are put on that, that the resultant bookkeeping is performed correctly.

1. PR 123 is opened and set to target branches x, y, and z 
2. PR 123 is reviewed and merged
3. Trop opens a backport to z, but can't backport to x and y
4. A maintainer opens a manual backport to y and adds a target to x, which shows it will be clean
5. When the manual backport to y is merged, trop opens a backport from y to x
6. When the auto-backport to x is merged, the original PR 123 should have its label updated to reflect that and the target label should be removed from the PR to y.

2024-09-10 17:31 UTC, VerteDinde approved these changes

2024-09-10 19:19 UTC, dsanders11 requested changes

2024-09-10 19:19 UTC, dsanders11 commented on src/utils.ts
> +      const needsManualLabel = PRStatus.IN_FLIGHT + targetBranch;
```suggestion
      const needsManualLabel = PRStatus.NEEDS_MANUAL + targetBranch;
```

2024-09-11 09:32 UTC, dsanders11 approved these changes

2024-09-11 13:28 UTC, merged